/* See mctiny.md for documentation. */

/* For implementors: This file is auto-generated by mctiny.py; do not edit. */
/* See mctiny.py for the underlying calculations. */

#ifndef mctiny_h
#define mctiny_h

#include "crypto_kem_mceliece6960119.h"

#define mctiny_PUBLICKEYBYTES crypto_kem_mceliece6960119_PUBLICKEYBYTES
#define mctiny_SECRETKEYBYTES crypto_kem_mceliece6960119_SECRETKEYBYTES
#define mctiny_CIPHERTEXTBYTES crypto_kem_mceliece6960119_CIPHERTEXTBYTES
#define mctiny_SESSIONKEYBYTES crypto_kem_mceliece6960119_BYTES

#define mctiny_keypair crypto_kem_mceliece6960119_keypair
#define mctiny_enc crypto_kem_mceliece6960119_enc
#define mctiny_dec crypto_kem_mceliece6960119_dec

#define mctiny_M 13
#define mctiny_MMASK 8191
#define mctiny_N 6960
#define mctiny_T 119
#define mctiny_ROWBITS 5413
#define mctiny_ROWBYTES 677
#define mctiny_COLBITS 1547
#define mctiny_COLBYTES 194

#define mctiny_EBYTES 870

#define mctiny_X 680
#define mctiny_XBYTES 85
#define mctiny_COLBLOCKS 8

#define mctiny_Y 13
#define mctiny_YBYTES 2
#define mctiny_ROWBLOCKS 119
#define mctiny_BLOCKBYTES 1105

#define mctiny_V 7

#define mctiny_PIECES 17

#define mctiny_PIECEBYTES 12

#define mctiny_COOKIE0BYTES 81
#define mctiny_COOKIEBLOCKBYTES 19
#define mctiny_COOKIE9BYTES 49

#define mctiny_QUERY0BYTES 810
#define mctiny_REPLY0BYTES 121
#define mctiny_QUERY1BYTES 1226
#define mctiny_REPLY1BYTES 140
#define mctiny_QUERY2BYTES 1185
#define mctiny_REPLY2BYTES 133
#define mctiny_QUERY3BYTES 315
#define mctiny_REPLY3BYTES 315

extern int mctiny_seedisvalid(const unsigned char *);
extern void mctiny_seed2e(unsigned char *,const unsigned char *);

extern void mctiny_pk2block(unsigned char *,const unsigned char *,int,int);
extern void mctiny_eblock2syndrome(unsigned char *,const unsigned char *,const unsigned char *,int);

extern void mctiny_pieceinit(unsigned char *,const unsigned char *,int);
extern void mctiny_pieceabsorb(unsigned char *,const unsigned char *,int);

extern void mctiny_mergepieces(unsigned char *,const unsigned char (*)[mctiny_PIECEBYTES]);

extern void mctiny_finalize(unsigned char *, unsigned char *,const unsigned char *,const unsigned char *);

#endif
